[package]
name = "rust_renderer"
version = "0.1.0"
authors = ["hjbyt <sopu00@gmail.com>"]

[dependencies]
image = "*"
rand = "*"
threadpool = "*"
num_cpus = "*"

[profile.test]
opt-level = 1
#lto = true